import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google"

const raleway = Raleway({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "UTS | ENROLLMENT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} bg-slate-200`}
      >
        {children}
      </body>
    </html>
  );
}
